### ISSUE TITLE
Open us_ALEX example

### ISSUE THREAD

**Issue by kfriedl** [Photon-Data/photon_hdf5_reading_examples#3]
I'm trying to open the us-ALEX read example files, but only get an error message. I can view the ns-ALEX file without problems. I'm using jupyter notebook 1.0.0 and python 3.5.2.

**Comment by tritemio** [comment]
@kfriedl, thank you for reporting the issue.

I just tried running the notebooks with python 3.5.2 and they all run successful. The notebooks were a little old and were using a python 2 kernel by default. Now I updated them (re-executing them with python 3.5 and saving them with jupyter notebook 5).

Can you try redownload the notebook and try again?
If the error persists, can you please copy/paste the error message and code-cell just before the error?

Note also that these notebooks are example of how to load Photon-HDF5 in python and are supposed to be example for developers developing custom software. If you just want to analyze the file, then you can directly use [FRETBursts](http://tritemio.github.io/FRETBursts/). In particular for usALEX files you should run the notebook:

- [FRETBursts - μs-ALEX smFRET burst analysis](http://nbviewer.jupyter.org/github/tritemio/FRETBursts_notebooks/blob/master/notebooks/FRETBursts%20-%20us-ALEX%20smFRET%20burst%20analysis.ipynb)

You can find and download all FRETBursts notebooks [here](https://github.com/tritemio/FRETBursts_notebooks#fretbursts-notebooks).

**Comment by kfriedl** [comment]
This is the message i get:
![error_message](https://cloud.githubusercontent.com/assets/27196897/24907722/9eea421a-1ebd-11e7-9420-4fd49124c80b.png)
Unfortunately I'm not using anaconda. I started jupyter from command line and tried to view the file via browser application. Maybe the command line output contains any clue:
![code_cell](https://cloud.githubusercontent.com/assets/27196897/24908175/605b5bea-1ebf-11e7-935d-b6c7112eca0d.png)
Thank you!

**Comment by tritemio** [comment]
The problem is simply that you didn't downloaded the notebook but an HTML page. To download notebooks from github, a safe way is downloading the ZIP of the full repository (click on [Download ZIP] button).

See the [README](https://github.com/Photon-HDF5/photon_hdf5_reading_examples#photon-hdf5-reading-examples) of this repository.

To download the FRETBursts notebooks, instead, see [here](https://github.com/tritemio/FRETBursts_notebooks#fretbursts-notebooks).

**Comment by kfriedl** [comment]
Ok, that works. Thank you very much!

**Comment by tritemio** [comment]
Perfect, feel free to report any other issue.
